name: generate pdf
on:
  push:
    paths:
      - 'lab*/**.ipynb'

jobs:
  generate_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install nbconvert ipykernel scipy pint numpy matplotlib pandas open-atmos-jupyter-utils
      - run: sudo apt-get install pandoc inkscape texlive-xetex texlive-fonts-recommended
      - run: |
          for file in $(find lab* -type f -name "*.ipynb"); do
            python -m nbconvert --to pdf --execute "$file"
          done

      - uses: actions/upload-artifact@v4
        with:
          path: lab*/*.pdf